-- Road to Pharmacy KKU
-- Run this file in Supabase Dashboard > SQL Editor.
-- The frontend must use Supabase Auth so auth.uid() is available.

create table if not exists public.study_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  week_number smallint not null check (week_number between 1 and 52),
  day_name text not null check (day_name in ('จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์', 'อาทิตย์')),
  title text not null default '',
  subject text not null default '',
  duration_hours numeric(3,1) not null default 0 check (duration_hours >= 0 and duration_hours <= 24),
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedule_templates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  row_number smallint not null check (row_number between 1 and 24),
  time_label text not null,
  monday text not null default '',
  tuesday text not null default '',
  wednesday text not null default '',
  thursday text not null default '',
  friday text not null default '',
  saturday text not null default '',
  sunday text not null default '',
  updated_at timestamptz not null default now(),
  unique (user_id, row_number)
);

create index if not exists study_tasks_user_week_idx
  on public.study_tasks (user_id, week_number);

create index if not exists study_tasks_user_completed_idx
  on public.study_tasks (user_id, completed);

alter table public.study_tasks enable row level security;
alter table public.schedule_templates enable row level security;

drop policy if exists "Users can read their study tasks" on public.study_tasks;
create policy "Users can read their study tasks"
  on public.study_tasks for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their study tasks" on public.study_tasks;
create policy "Users can insert their study tasks"
  on public.study_tasks for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their study tasks" on public.study_tasks;
create policy "Users can update their study tasks"
  on public.study_tasks for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their study tasks" on public.study_tasks;
create policy "Users can delete their study tasks"
  on public.study_tasks for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can read their schedule" on public.schedule_templates;
create policy "Users can read their schedule"
  on public.schedule_templates for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their schedule" on public.schedule_templates;
create policy "Users can insert their schedule"
  on public.schedule_templates for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their schedule" on public.schedule_templates;
create policy "Users can update their schedule"
  on public.schedule_templates for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their schedule" on public.schedule_templates;
create policy "Users can delete their schedule"
  on public.schedule_templates for delete
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists study_tasks_updated_at on public.study_tasks;
create trigger study_tasks_updated_at
before update on public.study_tasks
for each row execute procedure public.set_updated_at();

drop trigger if exists schedule_templates_updated_at on public.schedule_templates;
create trigger schedule_templates_updated_at
before update on public.schedule_templates
for each row execute procedure public.set_updated_at();
